FROM python:3.11
LABEL maintainer="christianmbookout@gmail.com"

COPY api/ ./

RUN pip install -r requirements.txt

EXPOSE 5000

CMD python -m waitress --listen=192.168.1.84:5000 --call app:create_app